name: cascade
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - ipywidgets
  - h5py
  - jupyter
  - pip
  - pip:
      - tensorflow  # Only if you plan to use the deep learning parts 